import { getRawDb } from "@/db/raw";
import { requireTeacherApi } from "@/app/teacher-auth";

type EditItem={type:string;prompt:string;options?:string[];correctAnswer?:string;explanation?:string;points?:number};
type ItemRow={id:number;type:string;prompt:string;optionsJson:string;correctAnswer:string|null;explanation:string;points:number};
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){if(!await requireTeacherApi())return Response.json({error:"ไม่มีสิทธิ์"},{status:403});const id=Number((await params).id);const db=getRawDb();const quiz=await db.prepare(`SELECT id,room_code AS roomCode,title,description,category,duration_minutes AS durationMinutes,published FROM quizzes WHERE id=?`).bind(id).first();if(!quiz)return Response.json({error:"ไม่พบแบบฝึก"},{status:404});const items=await db.prepare(`SELECT id,type,prompt,options_json AS optionsJson,correct_answer AS correctAnswer,explanation,points FROM quiz_items WHERE quiz_id=? ORDER BY position`).bind(id).all<ItemRow>();return Response.json({quiz,items:items.results.map(x=>({...x,options:JSON.parse(x.optionsJson||"[]")}))});}

export async function PUT(request:Request,{params}:{params:Promise<{id:string}>}){if(!await requireTeacherApi())return Response.json({error:"ไม่มีสิทธิ์"},{status:403});const id=Number((await params).id);const b=await request.json() as {title?:string;description?:string;category?:string;durationMinutes?:number;published?:boolean;items?:EditItem[]};const db=getRawDb();const count=await db.prepare(`SELECT COUNT(*) AS n FROM quiz_submissions WHERE quiz_id=?`).bind(id).first<{n:number}>();if(Number(count?.n)>0)return Response.json({error:"แบบฝึกนี้มีผู้ส่งแล้ว จึงแก้โจทย์ไม่ได้ เพื่อรักษาความถูกต้องของคะแนน"},{status:409});if(!b.title?.trim()||!Array.isArray(b.items)||!b.items.length)return Response.json({error:"ข้อมูลไม่ครบ"},{status:400});
  await db.prepare(`UPDATE quizzes SET title=?,description=?,category=?,duration_minutes=?,published=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(b.title.trim(),String(b.description??""),String(b.category??"แบบฝึกเพิ่มเติม"),Math.max(1,Number(b.durationMinutes)||20),b.published?1:0,id).run();await db.prepare(`DELETE FROM quiz_items WHERE quiz_id=?`).bind(id).run();await db.batch(b.items.map((x:EditItem,i:number)=>db.prepare(`INSERT INTO quiz_items (quiz_id,position,type,prompt,options_json,correct_answer,explanation,points) VALUES (?,?,?,?,?,?,?,?)`).bind(id,i+1,x.type,String(x.prompt).trim(),JSON.stringify(x.options??[]),x.type==="essay"?null:String(x.correctAnswer??""),String(x.explanation??""),Math.max(1,Number(x.points)||1))));return Response.json({updated:true});}
